apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxyd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: ha-proxy
        image: asadis7171/ha-proxy
        ports:
        - containerPort: 80
