apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      hostname: nodejsserver01
      containers:
      - name: ha-proxy
        image: asadis7171/node-js
        ports:
        - containerPort: 8081
