
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      hostname: redisnode01
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379